spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1/springcloud_sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  rabbitmq:
    host: 10.1.100.34
    port: 5672
    username: test
    password: 123456
  redis:
    host: 10.1.100.34
    port: 6379
    password: xc123#
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
